services:
  ctan-mirror:
    build: .
    container_name: ctan-mirror
    environment:
      # Pick a unique minute/hour so public CTAN mirrors do not all sync at once.
      CTAN_SYNC_CRON: "21 * * * *"
      HOST: mirror.example.com
    volumes:
      - ./ctan-data:/var/www/html/tex-archive
    restart: always
    labels:
      traefik.enable: true
      traefik.http.routers.ctan.rule: Host(`mirror.example.com`) # replace this
      traefik.http.routers.ctan.entrypoints: websecure
      traefik.http.routers.ctan.tls: true
      traefik.http.routers.ctan.tls.certresolver: tls_resolver
      traefik.http.routers.ctan.service: ctan
      traefik.http.services.ctan.loadbalancer.server.port: 80
      traefik.http.routers.ctan.middlewares: default@file
    networks:
      - proxy

networks:
  proxy:
    external: true
